# Generated by Django 4.2.2 on 2023-06-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classthreeyears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('graduates', models.CharField(max_length=50)),
                ('graduatesdoctor', models.CharField(max_length=50)),
                ('graduatesmaster', models.CharField(max_length=50)),
                ('entrants', models.CharField(max_length=50)),
                ('entrantsdoctor', models.CharField(max_length=50)),
                ('entrantsmaster', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='itkyweibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=16383)),
                ('topic', models.TextField(max_length=16383)),
            ],
        ),
        migrations.CreateModel(
            name='itkyzhihu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=16383)),
                ('title', models.TextField(max_length=16383)),
            ],
        ),
        migrations.CreateModel(
            name='jn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('applicants', models.CharField(max_length=50)),
                ('enrollment', models.CharField(max_length=50)),
                ('tm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='kyweibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=16383)),
                ('topic', models.TextField(max_length=16383)),
            ],
        ),
        migrations.CreateModel(
            name='kyzhihu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=16383)),
                ('title', models.TextField(max_length=16383)),
            ],
        ),
        migrations.CreateModel(
            name='totalthreeyears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('graduatesman', models.CharField(max_length=50)),
                ('graduatesfemale', models.CharField(max_length=50)),
                ('entrantsman', models.CharField(max_length=50)),
                ('entrantsfemale', models.CharField(max_length=50)),
                ('graduates', models.CharField(max_length=50)),
                ('entrants', models.CharField(max_length=50)),
                ('graduatesdoctor', models.CharField(max_length=50)),
                ('graduatesmaster', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('entrantsdoctor', models.CharField(max_length=50)),
                ('entrantsmaster', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='zb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('applicants', models.CharField(max_length=50)),
                ('enrollment', models.CharField(max_length=50)),
                ('tm', models.CharField(max_length=50)),
            ],
        ),
    ]
